import fs from 'fs';
import { LANGUAGES, TRANSLATIONS } from './src/constants/translations.js';

const filePath = './src/constants/translations.js';

const newTranslations = {
  "dob": { English: "Date of Birth", Malayalam: "ജനന തീയതി", Hindi: "जन्म तिथि" },
  "gender": { English: "Gender", Malayalam: "ലിംഗം", Hindi: "लिंग" },
  "experience": { English: "Exp", Malayalam: "പ്രവൃത്തിപരിചയം", Hindi: "अनुभव" },
  "preferred_areas": { English: "Preferred Areas", Malayalam: "മുൻഗണനാ മേഖലകൾ", Hindi: "पसंदीदा क्षेत्र" },
  "save_changes": { English: "Save Changes", Malayalam: "മാറ്റങ്ങൾ സംരക്ഷിക്കുക", Hindi: "बदलाव सहेजें" },
  "jobs_label": { English: "Jobs", Malayalam: "ജോലികൾ", Hindi: "नौकरियां" },
  "earnings_label": { English: "Earnings", Malayalam: "വരുമാനം", Hindi: "कमाई" },
  "mission_focus": { English: "Current Assignment", Malayalam: "നിലവിലെ ചുമതല", Hindi: "वर्तमान कार्य" },
  "shift_proof": { English: "Shift Logs & Proof", Malayalam: "ഷിഫ്റ്റ് ലോഗുകളും തെളിവുകളും", Hindi: "शिफ्ट लॉग और प्रमाण" },
  "loc_verified": { English: "Verified", Malayalam: "സ്ഥിരീകരിച്ചു", Hindi: "सत्यापित" },
  "task_audit": { English: "Mission Task Audit", Malayalam: "മിഷൻ ടാസ്ക് ഓഡിറ്റ്", Hindi: "मिशन कार्य ऑडिट" },
  "forensic_audit": { English: "Forensic Audit Metadata", Malayalam: "ഫോറൻസിക് ഓഡിറ്റ് മെറ്റാഡാറ്റ", Hindi: "फोरेंसिक ऑडिट मेटाडेटा" },
  "performance_metrics": { English: "Performance Analytics", Malayalam: "പ്രകടന വിശകലനം", Hindi: "प्रदर्शन विश्लेषण" },
  "wage": { English: "Wage", Malayalam: "വേതനം", Hindi: "वेतन" },
  "manage_job_postings": { English: "Industrial Asset Management", Malayalam: "വ്യാവസായിക അസറ്റ് മാനേജ്‌മെന്റ്", Hindi: "औद्योगिक संपत्ति प्रबंधन" },
  "live_jobs": { English: "ACTIVE", Malayalam: "സജീവം", Hindi: "सक्रिय" },
  "draft_jobs": { English: "DRAFTS", Malayalam: "ഡ്രാഫ്റ്റുകൾ", Hindi: "ड्राफ्ट" },
  "no_jobs_found": { English: "EMPTY INVENTORY", Malayalam: "ഒഴിഞ്ഞ ഇൻവെന്ററി", Hindi: "खाली सूची" },
  "live_job": { English: "LIVE DEPLOYMENT", Malayalam: "തത്സമയ വിന്യാസം", Hindi: "लाइव परिनियोजन" },
  "draft_mode": { English: "OFFLINE DRAFT", Malayalam: "ഓഫ്‌ലൈൻ ഡ്രാഫ്റ്റ്", Hindi: "ऑफ़लाइन ड्राफ्ट" },
  "modify": { English: "RECONFIGURE", Malayalam: "പുനഃക്രമീകരിക്കുക", Hindi: "पुनर्गठित करें" },
  "reviews": { English: "REVIEW CANDIDATES", Malayalam: "ഉദ്യോഗാർത്ഥികളെ അവലോകനം ചെയ്യുക", Hindi: "उम्मीदवारों की समीक्षा करें" },
  "check_in_out": { English: "MISSION LOGS // BIOMETRIC VERIFICATION", Malayalam: "മിഷൻ ലോഗുകൾ // ബയോമെട്രിക് സ്ഥിരീകരണം", Hindi: "मिशन लॉग // बायोमेट्रिक सत्यापन" },
  "site_evidence": { English: "FIELD EVIDENCE", Malayalam: "ഫീൽഡ് തെളിവുകൾ", Hindi: "फील्ड साक्ष्य" },
  "photo": { English: "OPTIC", Malayalam: "ചിത്രം", Hindi: "चित्र" },
  "video": { English: "STREAM", Malayalam: "വീഡിയോ", Hindi: "वीडियो" },
  "report": { English: "LOG", Malayalam: "ലോഗ് ചെയ്യുക", Hindi: "लॉग" },
  "take_selfie": { English: "BIOMETRIC_CAPTURE", Malayalam: "ബയോമെട്രിക് ക്യാപ്ചർ", Hindi: "बायोमेट्रिक कैप्चर" },
  "finish_shift": { English: "Check Out", Malayalam: "ചെക്ക് ഔട്ട്", Hindi: "चेक आउट" },
  "start_shift": { English: "Check In", Malayalam: "ചെക്ക് ഇൻ", Hindi: "चेक इन" },
  "benefits_title": { English: "Benefits", Malayalam: "ആനുകൂല്യങ്ങൾ", Hindi: "लाभ" },
  "worker_benefits": { English: "Worker Benefits", Malayalam: "തൊഴിലാളി ആനുകൂല്യങ്ങൾ", Hindi: "श्रमिक लाभ" },
  "benefits_subtitle": { English: "Your safety and health are our priority.", Malayalam: "നിങ്ങളുടെ സുരക്ഷിതത്വവും ആരോഗ്യവുമാണ് ഞങ്ങളുടെ മുൻഗണന.", Hindi: "आपकी सुरक्षा और स्वास्थ्य हमारी प्राथमिकता है।" },
  "membership_status": { English: "Membership Status", Malayalam: "അംഗത്വ നില", Hindi: "सदस्यता स्थिति" },
  "silver_partner": { English: "Silver Partner", Malayalam: "സിൽവർ പങ്കാളി", Hindi: "सिल्वर पार्टनर" },
  "coming_soon": { English: "Coming Soon", Malayalam: "ഉടൻ വരുന്നു", Hindi: "जल्द आ रहा है" },
  "accidental_work_cover": { English: "Accidental Work Cover", Malayalam: "അപകട ഇൻഷുറൻസ് പരിരക്ഷ", Hindi: "दुर्घटना कार्य कवर" },
  "provider": { English: "Provider", Malayalam: "സേവന ദാതാവ്", Hindi: "प्रदाता" },
  "coverage_1l": { English: "₹1,00,000 Coverage", Malayalam: "₹1,00,000 പരിരക്ഷ", Hindi: "₹1,00,000 कवरेज" },
  "instant_claim_help": { English: "Instant Claim Help", Malayalam: "തൽക്ഷണ ക്ലെയിം സഹായം", Hindi: "तत्काल दावा सहायता" },
  "family_support": { English: "Family Support", Malayalam: "കുടുംബ പിന്തുണ", Hindi: "पारिवारिक सहायता" },
  "healthcare_plan": { English: "Healthcare Plan", Malayalam: "ആരോഗ്യ പരിപാലന പദ്ധതി", Hindi: "स्वास्थ्य सेवा योजना" },
  "wellness_center": { English: "Wellness Center", Malayalam: "വെൽനസ് സെന്റർ", Hindi: "कल्याण केंद्र" },
  "my_earnings_chip": { English: "My Earnings 💰", Malayalam: "എന്റെ വരുമാനം 💰", Hindi: "मेरी कमाई 💰" },
  "check_in_help_chip": { English: "Check-in Help 📍", Malayalam: "ചെക്ക് ഇൻ സഹായം 📍", Hindi: "चेक-इन सहायता 📍" },
  "find_gigs_chip": { English: "Find Gigs 🔍", Malayalam: "ജോലികൾ കണ്ടെത്തുക 🔍", Hindi: "गिग्स खोजें 🔍" },
  "policies_chip": { English: "Policies 📜", Malayalam: "നയങ്ങൾ 📜", Hindi: "नीतियां 📜" },
  "predict_demand_chip": { English: "Predict Demand 📈", Malayalam: "ഡിമാൻഡ് പ്രവചിക്കുക 📈", Hindi: "मांग का पूर्वानुमान 📈" },
  "hiring_health_chip": { English: "Hiring Health 🩺", Malayalam: "നിയമന ആരോഗ്യം 🩺", Hindi: "भर्ती स्वास्थ्य 🩺" },
  "wage_opt_chip": { English: "Wage Optimization 💰", Malayalam: "വേതന ഒപ്റ്റിമൈസേഷൻ 💰", Hindi: "वेतन अनुकूलन 💰" },
  "worker_trends_chip": { English: "Worker Trends 📊", Malayalam: "തൊഴിലാളി പ്രവണതകൾ 📊", Hindi: "श्रमिक प्रवृत्तियां 📊" },
  "just_now": { English: "JUST NOW", Malayalam: "ഇപ്പോൾത്തന്നെ", Hindi: "अभी-अभी" },
  "admin_bot_greeting": { English: "Hello! I'm Genie Ops, your operations assistant. How can I help?", Malayalam: "ഹലോ! ഞാൻ ജീനി ഓപ്‌സ്, നിങ്ങളുടെ പ്രവർത്തന സഹായിയാണ്. ഞാൻ എങ്ങനെ സഹായിക്കണം?", Hindi: "नमस्ते! मैं जिनी ऑप्स हूं, आपका संचालन सहायक। मैं कैसे मदद कर सकता हूं?" },
  "worker_bot_greeting": { English: "Hi! I'm Genie, your personal job assistant. How can I help you today?", Malayalam: "ഹായ്! ഞാൻ ജീനി, നിങ്ങളുടെ വ്യക്തിഗത ജോലി സഹായിയാണ്. ഇന്ന് ഞാൻ നിങ്ങളെ എങ്ങനെ സഹായിക്കണം?", Hindi: "नमस्ते! मैं जिनी हूं, आपका व्यक्तिगत नौकरी सहायक। आज मैं आपकी कैसे मदद कर सकता हूं?" },
  "processed_request": { English: "I processed your request!", Malayalam: "ഞാൻ നിങ്ങളുടെ അഭ്യർത്ഥന പ്രോസസ്സ് ചെയ്തു!", Hindi: "मैंने आपके अनुरोध को संसाधित कर दिया है!" },
  "brain_sync_error": { English: "Brain sync error! 🧞", Malayalam: "ബ്രെയിൻ സമന്വയ പിശക്! 🧞", Hindi: "मस्तिष्क सिंक त्रुटि! 🧞" },
  "genie_ops": { English: "Ops AI", Malayalam: "ഓപ്‌സ് എഐ", Hindi: "ऑप्स एआई" },
  "genie_ai": { English: "Genie AI", Malayalam: "ജീനി എഐ", Hindi: "जिनी एआई" },
  "ready_to_help": { English: "Ready to help", Malayalam: "സഹായിക്കാൻ തയ്യാറാണ്", Hindi: "मदद के लिए तैयार" },
  "online": { English: "ONLINE", Malayalam: "ഓൺ‌ലൈൻ", Hindi: "ऑनलाइन" },
  "suggestions": { English: "Suggestions", Malayalam: "നിർദ്ദേശങ്ങൾ", Hindi: "सुझाव" },
  "ask_genie_ops": { English: "Ask Genie Ops...", Malayalam: "ജീനി ഓപ്‌സിനോട് ചോദിക്കുക...", Hindi: "जिनी ऑप्स से पूछें..." },
  "ask_me_anything": { English: "Ask me anything...", Malayalam: "എന്നോട് എന്ത് വേണമെങ്കിലും ചോദിക്കൂ...", Hindi: "मुझसे कुछ भी पूछें..." },
  "working_days": { English: "WORKING DAYS", Malayalam: "ജോലി ദിവസങ്ങൾ", Hindi: "कार्य दिवस" },
  "payment_date": { English: "PAYMENT DATE (1-31)", Malayalam: "പേയ്‌മെന്റ് തീയതി (1-31)", Hindi: "भुगतान तिथि (1-31)" },
  "placeholder_payment_date": { English: "e.g. 1 for 1st of month", Malayalam: "ഉദാഹരണത്തിന് മാസത്തിലെ ഒന്നാം തീയതിക്ക് 1", Hindi: "उदा. महीने की पहली तारीख के लिए 1" },
  "my_earnings": { English: "My Earnings", Malayalam: "എന്റെ വരുമാനം", Hindi: "मेरी कमाई" },
  "track_income": { English: "Track your income and payouts", Malayalam: "നിങ്ങളുടെ വരുമാനവും പേഔട്ടുകളും ട്രാക്ക് ചെയ്യുക", Hindi: "अपनी आय और भुगतान ट्रैक करें" },
  "increase_last_week": { English: "+12% from last week", Malayalam: "കഴിഞ്ഞ ആഴ്ചയേക്കാൾ +12% കൂടുതൽ", Hindi: "पिछले सप्ताह से +12%" },
  "withdraw_cash": { English: "Withdraw Cash", Malayalam: "പണം പിൻവലിക്കുക", Hindi: "नकद निकालें" },
  "export": { English: "Export", Malayalam: "കയറ്റുമതി ചെയ്യുക", Hindi: "निर्यात करें" },
  "week": { English: "Week", Malayalam: "ആഴ്ച", Hindi: "सप्ताह" },
  "days": { English: "Days", Malayalam: "ദിവസങ്ങൾ", Hindi: "दिन" },
  "avg": { English: "Avg", Malayalam: "ശരാശരി", Hindi: "औसत" },
  "weekly_performance": { English: "Weekly Performance", Malayalam: "പ്രതിവാര പ്രകടനം", Hindi: "साप्ताहिक प्रदर्शन" },
  "recent_payouts": { English: "Recent Payouts", Malayalam: "സമീപകാല പേഔട്ടുകൾ", Hindi: "हालिया भुगतान" },
  "paid": { English: "PAID", Malayalam: "പണം നൽകി", Hindi: "भुगतान किया गया" },
  "set_earnings_goal": { English: "Set Earnings Goal", Malayalam: "വരുമാന ലക്ഷ്യം സജ്ജമാക്കുക", Hindi: "कमाई का लक्ष्य निर्धारित करें" },
  "plan_with_ai": { English: "Plan your schedule with AI helper", Malayalam: "എഐ സഹായി ഉപയോഗിച്ച് നിങ്ങളുടെ ഷെഡ്യൂൾ പ്ലാൻ ചെയ്യുക", Hindi: "एआई सहायक के साथ अपने कार्यक्रम की योजना बनाएं" },
  "withdraw_subtitle": { English: "Transfer your earnings to your bank account instantly.", Malayalam: "നിങ്ങളുടെ വരുമാനം ബാങ്ക് അക്കൗണ്ടിലേക്ക് തൽക്ഷണം മാറ്റുക.", Hindi: "अपनी कमाई को तुरंत अपने बैंक खाते में स्थानांतरित करें।" },
  "available_balance": { English: "Available Balance", Malayalam: "ലഭ്യമായ ബാലൻസ്", Hindi: "उपलब्ध शेष राशि" },
  "withdrawal_initiated": { English: "Withdrawal initiated! Funds will arrive shortly.", Malayalam: "പിൻവലിക്കൽ ആരംഭിച്ചു! പണം ഉടൻ ലഭിക്കും.", Hindi: "निकासी शुरू हो गई है! धनराशि जल्द ही आ जाएगी।" },
  "withdraw_now": { English: "Withdraw Now", Malayalam: "ഇപ്പോൾ പിൻവലിക്കുക", Hindi: "अभी निकालें" },
  "away_unit": { English: "2.4 KM AWAY", Malayalam: "2.4 കി.മീ അകലെ", Hindi: "2.4 किमी दूर" },
  "match": { English: "MATCH", Malayalam: "പൊരുത്തം", Hindi: "मिलान" },
  "urgent": { English: "URGENT", Malayalam: "അടിയന്തിരം", Hindi: "तत्काल" },
  "per_day": { English: "PER DAY", Malayalam: "പ്രതിദിനം", Hindi: "प्रति दिन" },
  "view_details": { English: "VIEW MISSION", Malayalam: "ദൗത്യം കാണുക", Hindi: "मिशन देखें" },
  "banner_cash_tag": { English: "⚡ Quick Cash", Malayalam: "⚡ പെട്ടെന്ന് പണം", Hindi: "⚡ त्वरित नकद" },
  "banner_cash_title": { English: "Instant Loan up to ₹1,00,000", Malayalam: "₹1,00,000 വരെയുള്ള തൽക്ഷണ വായ്പ", Hindi: "₹1,00,000 तक का तत्काल ऋण" },
  "banner_cash_desc": { English: "Zero fee · Apply in 2 mins →", Malayalam: "പൂജ്യം ഫീസ് · 2 മിനിറ്റിനുള്ളിൽ അപേക്ഷിക്കുക →", Hindi: "शून्य शुल्क · 2 मिनट में आवेदन करें →" },
  "banner_refer_tag": { English: "🤝 Refer & Earn", Malayalam: "🤝 റഫർ ചെയ്യുക & നേടുക", Hindi: "🤝 रेफ़र करें और कमाएं" },
  "banner_refer_title": { English: "Get ₹500 per friend you refer", Malayalam: "നിങ്ങൾ റഫർ ചെയ്യുന്ന ഓരോ സുഹൃത്തിനും ₹500 നേടുക", Hindi: "प्रत्येक मित्र को रेफ़र करने पर ₹500 पाएं" },
  "banner_refer_desc": { English: "No limit · Instant payout →", Malayalam: "പരിധിയില്ല · തൽക്ഷണ പേഔട്ട് →", Hindi: "कोई सीमा नहीं · तत्काल भुगतान →" },
  "banner_insurance_tag": { English: "🛡️ Free Insurance", Malayalam: "🛡️ സൗജന്യ ഇൻഷുറൻസ്", Hindi: "🛡️ निःशुल्क बीमा" },
  "banner_insurance_title": { English: "₹2L accidental cover — free!", Malayalam: "₹2L അപകട പരിരക്ഷ — സൗജന്യമായി!", Hindi: "₹2L दुर्घटना कवर — निःशुल्क!" },
  "banner_insurance_desc": { English: "Active for all workers →", Malayalam: "എല്ലാ തൊഴിലാളികൾക്കും സജീവം →", Hindi: "सभी श्रमिकों के लिए सक्रिय →" },
  "admin_label": { English: "Genie Partner", Malayalam: "ജീനി പങ്കാളി", Hindi: "जिनी पार्टनर" },
  "worker_label": { English: "Worker", Malayalam: "തൊഴിലാളി", Hindi: "श्रमिक" },
  "good_morning": { English: "Good morning", Malayalam: "സുപ്രഭാതം", Hindi: "शुभ प्रभात" },
  "good_afternoon": { English: "Good afternoon", Malayalam: "ശുഭ ഉച്ചനേരം", Hindi: "शुभ दोपहर" },
  "good_evening": { English: "Good evening", Malayalam: "ശുഭ സായാഹ്നം", Hindi: "शुभ संध्या" },
  "mission_verifications": { English: "Mission Verifications", Malayalam: "മിഷൻ പരിശോധനകൾ", Hindi: "मिशन सत्यापन" },
  "approved_by_hq": { English: "Verified by HQ", Malayalam: "ആസ്ഥാനം സ്ഥിരീകരിച്ചു", Hindi: "मुख्यालय द्वारा सत्यापित" },
  "today": { English: "Today", Malayalam: "ഇന്ന്", Hindi: "आज" },
  "job_genie_partner": { English: "JobGenie Partner", Malayalam: "ജോബ് ജീനി പങ്കാളി", Hindi: "जॉब जिनी पार्टनर" },
  "task_arrive": { English: "Arrive on time at the location", Malayalam: "കൃത്യസമയത്ത് സ്ഥലത്ത് എത്തിച്ചേരുക", Hindi: "समय पर स्थान पर पहुंचें" },
  "task_supervisor": { English: "Follow supervisor instructions", Malayalam: "സൂപ്പർവൈസറുടെ നിർദ്ദേശങ്ങൾ പാലിക്കുക", Hindi: "पर्यवेक्षक के निर्देशों का पालन करें" },
  "task_safe": { English: "Maintain a safe working environment", Malayalam: "സുരക്ഷിതമായ ജോലി സാഹചര്യം നിലനിർത്തുക", Hindi: "सुरक्षित कार्य वातावरण बनाए रखें" },
  "task_clock_out": { English: "Clock out after shift completion", Malayalam: "ഷിഫ്റ്റ് പൂർത്തിയായ ശേഷം ക്ലോക്ക് ഔട്ട് ചെയ്യുക", Hindi: "शिफ्ट पूरी होने के बाद क्लॉक आउट करें" },
  "req_fitness": { English: "Physical Fitness", Malayalam: "ശാരീരികക്ഷമത", Hindi: "शारीरिक फिटनेस" },
  "req_aadhaar": { English: "Aadhaar Card", Malayalam: "ആധാർ കാർഡ്", Hindi: "आधार कार्ड" },
  "req_phone": { English: "Android Phone", Malayalam: "ആൻഡ്രോയിഡ് ഫോൺ", Hindi: "एंड्रॉइड फोन" },
  "job_details": { English: "MISSION DATA", Malayalam: "മിഷൻ വിവരങ്ങൾ", Hindi: "मिशन डेटा" },
  "company_description_default": { English: "Leading industrial partner focused on high-efficiency workforce deployment.", Malayalam: "കാര്യക്ഷമതയേറിയ തൊഴിലാളി വിന്യാസത്തിൽ ശ്രദ്ധ കേന്ദ്രീകരിക്കുന്ന മുൻനിര വ്യാവസായിക പങ്കാളി.", Hindi: "उच्च दक्षता वाले कार्यबल परिनियोजन पर केंद्रित अग्रणी औद्योगिक भागीदार।" },
  "apply_for_job": { English: "INITIALIZE ENROLLMENT", Malayalam: "എൻറോൾമെന്റ് ആരംഭിക്കുക", Hindi: "नामांकन शुरू करें" },
  "leaderboard_title": { English: "Local Hub Ranking", Malayalam: "പ്രാദേശിക ഹബ് റാങ്കിംഗ്", Hindi: "स्थानीय हब रैंकिंग" },
  "hub_subtitle": { English: "Top earners in Adyar Hub", Malayalam: "അഡയാർ ഹബിലെ മികച്ച വരുമാനക്കാർ", Hindi: "अड्यार हब में सबसे ज्यादा कमाई करने वाले" },
  "genie_credit": { English: "Genie Credit", Malayalam: "ജീനി ക്രെഡിറ്റ്", Hindi: "जिनी क्रेडिट" },
  "personal_line": { English: "Personal Line", Malayalam: "വ്യക്തിഗത ലൈൻ", Hindi: "पर्सनल लाइन" },
  "operator": { English: "Operator", Malayalam: "ഓപ്പറേറ്റർ", Hindi: "ऑपरेटर" },
  "genie_user": { English: "Genie User", Malayalam: "ജീനി ഉപയോക്താവ്", Hindi: "जिनी उपयोगकर्ता" },
  "limit": { English: "Limit", Malayalam: "പരിധി", Hindi: "सीमा" },
  "limit_amount": { English: "₹1.0L", Malayalam: "₹1.0L", Hindi: "₹1.0L" },
  "verified": { English: "Verified", Malayalam: "സ്ഥിരീകരിച്ചു", Hindi: "सत्यापित" },
  "details_step": { English: "Details", Malayalam: "വിശദാംശങ്ങൾ", Hindi: "विवरण" },
  "eligibility_step": { English: "Eligibility", Malayalam: "യോഗ്യത", Hindi: "पात्रता" },
  "kyc_step": { English: "KYC", Malayalam: "കെവൈസി", Hindi: "केवाईसी" },
  "done_step": { English: "Done", Malayalam: "പൂർത്തിയായി", Hindi: "पूर्ण" },
  "credit_title": { English: "Credit", Malayalam: "ക്രെഡിറ്റ്", Hindi: "क्रेडिट" },
  "credit_subtitle": { English: "Quick & Easy financial support", Malayalam: "വേഗത്തിലും എളുപ്പത്തിലും സാമ്പത്തിക പിന്തുണ", Hindi: "त्वरित और आसान वित्तीय सहायता" },
  "select_amount": { English: "Select Amount", Malayalam: "തുക തിരഞ്ഞെടുക്കുക", Hindi: "राशि चुनें" },
  "max_amount": { English: "Max ₹1.0L", Malayalam: "പരമാവധി ₹1.0L", Hindi: "अधिकतम ₹1.0L" },
  "eligible": { English: "You're Eligible!", Malayalam: "നിങ്ങൾക്ക് യോഗ്യതയുണ്ട്!", Hindi: "आप पात्र हैं!" },
  "qualify_gold": { English: "You qualify for the Gold credit limit.", Malayalam: "നിങ്ങൾക്ക് ഗോൾഡ് ക്രെഡിറ്റ് പരിധിക്ക് അർഹതയുണ്ട്!", Hindi: "आप गोल्ड क्रेडिट सीमा के लिए पात्र हैं।" },
  "cibil_status": { English: "Index: 742 — Optimal", Malayalam: "സൂചിക: 742 — മികച്ചത്", Hindi: "सूचकांक: 742 — इष्टतम" },
  "work_history": { English: "Work History", Malayalam: "ജോലി ചരിത്രം", Hindi: "कार्य इतिहास" },
  "work_history_status": { English: "12 Jobs completed", Malayalam: "12 ജോലികൾ പൂർത്തിയാക്കി", Hindi: "12 कार्य पूर्ण" },
  "identity": { English: "Identity", Malayalam: "ഐഡന്റിറ്റി", Hindi: "पहचान" },
  "identity_status": { English: "Pending verification", Malayalam: "പരിശോധന പൂർത്തിയാകാനുണ്ട്", Hindi: "सत्यापन लंबित" },
  "verify_id": { English: "Verify ID", Malayalam: "ഐഡി പരിശോധിക്കുക", Hindi: "आईडी सत्यापित करें" },
  "verify_your_id": { English: "Verify your ID", Malayalam: "നിങ്ങളുടെ ഐഡി പരിശോധിക്കുക", Hindi: "अपनी आईडी सत्यापित करें" },
  "secure_verification": { English: "Safe and secure encrypted verification.", Malayalam: "സുരക്ഷിതവും എൻക്രിപ്റ്റ് ചെയ്തതുമായ പരിശോധന.", Hindi: "सुरक्षित और एन्क्रिप्टेड सत्यापन।" },
  "aadhaar_card": { English: "Aadhaar Card", Malayalam: "ആധാർ കാർഡ്", Hindi: "आधार कार्ड" },
  "front_back_req": { English: "Front & Back required", Malayalam: "മുൻവശവും പിൻവശവും ആവശ്യമാണ്", Hindi: "सामने और पीछे का भाग आवश्यक" },
  "pan_card": { English: "PAN Card", Malayalam: "പാൻ കാർഡ്", Hindi: "पैन कार्ड" },
  "clear_scan_req": { English: "Clear scan required", Malayalam: "വ്യക്തമായ സ്കാൻ ആവശ്യമാണ്", Hindi: "स्पष्ट स्कैन आवश्यक" },
  "selfie": { English: "Selfie", Malayalam: "സെൽഫി", Hindi: "सेल्फी" },
  "live_face_req": { English: "Live face verification", Malayalam: "ലൈവ് ഫേസ് വെരിഫിക്കേഷൻ", Hindi: "लाइव फेस सत्यापन" },
  "submitting": { English: "Submitting...", Malayalam: "സമർപ്പിക്കുന്നു...", Hindi: "सबमिट किया जा रहा है..." },
  "app_submitted": { English: "Your application has been submitted.", Malayalam: "നിങ്ങളുടെ അപേക്ഷ സമർപ്പിച്ചു.", Hindi: "आपका आवेदन सबमिट कर दिया गया है।" },
  "application_id": { English: "Application ID", Malayalam: "അപേക്ഷാ ഐഡി", Hindi: "आवेदन आईडी" },
  "requested": { English: "Requested", Malayalam: "അഭ്യർത്ഥിച്ചു", Hindi: "अनुरोधित" },
  "status": { English: "Status", Malayalam: "നില", Hindi: "स्थिति" },
  "processing_status": { English: "Processing", Malayalam: "പ്രോസസ്സ് ചെയ്യുന്നു", Hindi: "प्रसंस्करण" },
  "back_to_dashboard": { English: "Back to Dashboard", Malayalam: "ഡ്രാഷ്‌ബോർഡിലേക്ക് തിരികെ പോകുക", Hindi: "डैशबोर्ड पर वापस जाएं" },
  "status_pending_review": { English: "ANALYSIS", Malayalam: "വിശകലനം", Hindi: "विश्लेषण" },
  "rate": { English: "Rate Employer", Malayalam: "തൊഴിൽദാതാവിനെ വിലയിരുത്തുക", Hindi: "नियोक्ता को रेट करें" },
  "no_approved_jobs": { English: "NO_DEPLOYMENTS_AUTHORIZED", Malayalam: "വിന്യാസങ്ങൾക്ക് അനുമതി നൽകിയിട്ടില്ല", Hindi: "कोई परिनियोजन अधिकृत नहीं" },
  "welcome": { English: "Welcome!", Malayalam: "സ്വാഗതം!", Hindi: "स्वागत है!" },
  "setup_profile": { English: "Let's set up your profile", Malayalam: "നിങ്ങളുടെ പ്രൊഫൈൽ സജ്ജീകരിക്കാം", Hindi: "आइए आपकी प्रोफ़ाइल सेट करें" },
  "about_company": { English: "About your Company", Malayalam: "നിങ്ങളുടെ കമ്പനിയെക്കുറിച്ച്", Hindi: "आपकी कंपनी के बारे में" },
  "about_you": { English: "Tell us about you", Malayalam: "നിങ്ങളെക്കുറിച്ച് പറയുക", Hindi: "अपने बारे में बताएं" },
  "industry_sectors": { English: "Industry Sectors", Malayalam: "വ്യവസായ മേഖലകൾ", Hindi: "उद्योग क्षेत्र" },
  "skills_exp": { English: "Skills & Experience", Malayalam: "കഴിവുകളും പരിചയസമ്പത്തും", Hindi: "कौशल और अनुभव" },
  "company_vision": { English: "Company Vision", Malayalam: "കമ്പനി ദർശനം", Hindi: "कंपनी का दृष्टिकोण" },
  "your_preferences": { English: "Your Preferences", Malayalam: "നിങ്ങളുടെ മുൻഗണനകൾ", Hindi: "आपकी प्राथमिकताएं" },
  "onboarding_step1_desc": { English: "Start by sharing your basic details.", Malayalam: "നിങ്ങളുടെ അടിസ്ഥാന വിവരങ്ങൾ പങ്കിട്ടുകൊണ്ട് ആരംഭിക്കുക.", Hindi: "अपने बुनियादी विवरण साझा करके शुरुआत करें।" },
  "onboarding_step2_desc": { English: "Help us find the best matches for you.", Malayalam: "നല്ല പൊരുത്തങ്ങൾ കണ്ടെത്താൻ ഞങ്ങളെ സഹായിക്കൂ.", Hindi: "आपके लिए सर्वोत्तम मिलान खोजने में हमारी सहायता करें।" },
  "onboarding_step3_desc": { English: "Final details to get you started.", Malayalam: "നിങ്ങൾക്ക് ആരംഭിക്കാനുള്ള അവസാന വിശദാംശങ്ങൾ.", Hindi: "आपको आरंभ करने के लिए अंतिम विवरण।" },
  "company_name": { English: "Company Name", Malayalam: "കമ്പനിയുടെ പേര്", Hindi: "कंपनी का नाम" },
  "full_name": { English: "Full Name", Malayalam: "പൂർണ്ണമായ പേര്", Hindi: "पूरा नाम" },
  "company_name_placeholder": { English: "E.g. Logistics Corp", Malayalam: "ഉദാഹരണത്തിന് ലോജിസ്റ്റിക്സ് കോർപ്പറേഷൻ", Hindi: "उदा. लॉजिस्टिक्स कॉर्प" },
  "full_name_placeholder": { English: "Enter your full name", Malayalam: "നിങ്ങളുടെ പൂർണ്ണമായ പേര് നൽകുക", Hindi: "अपना पूरा नाम दर्ज करें" },
  "headquarters_placeholder": { English: "E.g. Mumbai, Delhi", Malayalam: "ഉദാഹരണത്തിന് മുംബൈ, ഡൽഹി", Hindi: "उदा. मुंबई, दिल्ली" },
  "other": { English: "Other", Malayalam: "മറ്റുള്ളവ", Hindi: "अन्य" },
  "primary_sector": { English: "Primary Sector", Malayalam: "പ്രധാന മേഖല", Hindi: "प्राथमिक क्षेत्र" },
  "experience_level": { English: "Experience Level (Years)", Malayalam: "പ്രവൃത്തിപരിചയം (വർഷങ്ങളിൽ)", Hindi: "अनुभव स्तर (वर्ष)" },
  "company_vision_placeholder": { English: "Describe your company culture and mission...", Malayalam: "നിങ്ങളുടെ കമ്പനി സംസ്കാരത്തെയും ദൗത്യത്തെയും കുറിച്ച് വിവരിക്കുക...", Hindi: "अपनी कंपनी की संस्कृति और मिशन का वर्णन करें..." },
  "preferred_areas_placeholder": { English: "E.g. Bangalore, Chennai...", Malayalam: "ഉദാഹരണത്തിന് ബാംഗ്ലൂർ, ചെന്നൈ...", Hindi: "उदा. बैंगलोर, चेन्नई..." },
  "smart_matching": { English: "Smart Matching", Malayalam: "സ്മാർട്ട് മാച്ചിംഗ്", Hindi: "स्मार्ट मिलान" },
  "personalized_helper": { English: "Personalized Helper", Malayalam: "വ്യക്തിഗത സഹായി", Hindi: "व्यक्तिगत सहायक" },
  "smart_matching_desc": { English: "We'll help you find the best workers.", Malayalam: "മികച്ച തൊഴിലാളികളെ കണ്ടെത്താൻ ഞങ്ങൾ നിങ്ങളെ സഹായിക്കും.", Hindi: "हम आपको सर्वोत्तम श्रमिक खोजने में मदद करेंगे।" },
  "personalized_helper_desc": { English: "I'll help you find the best jobs near you.", Malayalam: "നിങ്ങളുടെ അടുത്തുള്ള മികച്ച ജോലികൾ കണ്ടെത്താൻ ഞാൻ സഹായിക്കും.", Hindi: "मैं आपके पास सर्वोत्तम नौकरियां खोजने में आपकी मदद करूंगा।" },
  "complete_setup": { English: "Complete Setup", Malayalam: "സജ്ജീകരണം പൂർത്തിയാക്കുക", Hindi: "सेटअप पूरा करें" },
  "profile_title": { English: "MY PROFILE", Malayalam: "എന്റെ പ്രൊഫൈൽ", Hindi: "मेरी प्रोफ़ाइल" },
  "manage_account": { English: "GENIE OS // ACCOUNT MGMT", Malayalam: "ജീനി ഒഎസ് // അക്കൗണ്ട് മാനേജ്‌മെന്റ്", Hindi: "जिनी ओएस // खाता प्रबंधन" },
  "operations_label": { English: "Operations", Malayalam: "പ്രവർത്തനങ്ങൾ", Hindi: "संचालन" },
  "profile_strength": { English: "SECURITY CLEARANCE", Malayalam: "സുരക്ഷാ അനുമതി നില", Hindi: "सुरक्षा मंजूरी" },
  "achievements_label": { English: "Verified Credentials", Malayalam: "സ്ഥിരീകരിച്ച യോഗ്യതകൾ", Hindi: "सत्यापित क्रेडेंशियल" },
  "settings_label": { English: "Configuration", Malayalam: "കോൺഫിഗറേഷൻ", Hindi: "विन्यास" },
  "app_language": { English: "App Language", Malayalam: "ആപ്പ് ഭാഷ", Hindi: "ऐप की भाषा" },
  "select_language": { English: "Select Language", Malayalam: "ഭാഷ തിരഞ്ഞെടുക്കുക", Hindi: "भाषा चुनें" },
  "active_workers": { English: "Active Personnel", Malayalam: "സജീവ ജീവനക്കാർ", Hindi: "सक्रिय कर्मचारी" },
  "avg_work": { English: "Duty Duration", Malayalam: "ഡ്യൂട്ടി സമയം", Hindi: "कर्तव्य की अवधि" },
  "system_health": { English: "Node Integrity", Malayalam: "സിസ്റ്റം ആരോഗ്യം", Hindi: "नोड अखंडता" },
  "status_good": { English: "STABLE", Malayalam: "സുസ്ഥിരമാണ്", Hindi: "स्थिर" },
  "jobTitle": { English: "Industrial Task", Malayalam: "വ്യാവസായിക ജോലി", Hindi: "औद्योगिक कार्य" },
  "workerName": { English: "User", Malayalam: "ഉപയോക്താവ്", Hindi: "उपयोगकर्ता" },
  "role": { English: "Partner", Malayalam: "പങ്കാളി", Hindi: "भागीदार" },
  "on_site": { English: "ENGAGED", Malayalam: "ഏർപ്പെട്ടിരിക്കുന്നു", Hindi: "लगा हुआ" },
  "finished": { English: "TERMINATED", Malayalam: "പвобоപ്പിച്ചു", Hindi: "समाप्त" },
  "checkInTime": { English: "--:--", Malayalam: "--:--", Hindi: "--:--" },
  "checkOutTime": { English: "--:--", Malayalam: "--:--", Hindi: "--:--" },
  "tab_logs": { English: "LOGS", Malayalam: "ലോഗുകൾ", Hindi: "लॉग" },
  "tab_metrics": { English: "ANALYTICS", Malayalam: "വിശകലനം", Hindi: "विश्लेषिकी" },
  "tab_tracking": { English: "RADAR", Malayalam: "റഡാർ", Hindi: "रडार" },
  "monitor_realtime": { English: "Real-time Deployment Monitoring", Malayalam: "തത്സമയ വിന്യാസ നിരീക്ഷണം", Hindi: "वास्तविक समय परिनियोजन निगरानी" },
  "export_csv": { English: "EXPORT RAW", Malayalam: "വിവരങ്ങൾ കയറ്റുമതി ചെയ്യുക", Hindi: "रॉ डेटा निर्यात करें" },
  "rate_now": { English: "DEPLOY REVIEW", Malayalam: "അവലോകനം ചെയ്യുക", Hindi: "समीक्षा रेट करें" },
  "shield_active": { English: "Shield Active", Malayalam: "ഷീൽഡ് സജീവമാണ്", Hindi: "शील्ड सक्रिय" },
  "shield_offline": { English: "Shield Offline", Malayalam: "ഷീൽഡ് ഓഫ്ലൈനാണ്", Hindi: "शील्ड ऑफ़लाइन" },
  "safety_active_desc": { English: "Your location is being shared with trusted contacts", Malayalam: "നിങ്ങളുടെ ലൊക്കേഷൻ വിശ്വസ്തരായ കോൺടാക്റ്റുകളുമായി പങ്കിടുന്നു", Hindi: "आपका स्थान विश्वसनीय संपर्कों के साथ साझा किया जा रहा है" },
  "safety_offline_desc": { English: "Activate safety mode for live tracking and support.", Malayalam: "തത്സമയ ട്രാക്കിംഗിനും പിന്തുണക്കുമായി സുരക്ഷാ മോഡ് സജീവമാക്കുക.", Hindi: "लाइव ट्रैकिंग और सहायता के लिए सुरक्षा मोड सक्रिय करें।" },
  "deactivate_safety": { English: "Deactivate Safety Mode", Malayalam: "സുരക്ഷാ മോഡ് നിർജ്ജീവമാക്കുക", Hindi: "सुरक्षा मोड निष्क्रिय करें" },
  "activate_safety": { English: "Activate Safety Mode", Malayalam: "സുരക്ഷാ മോഡ് സജീവമാക്കുക", Hindi: "सुरक्षा मोड सक्रिय करें" },
  "turn_off_tracking": { English: "Turn off live tracking", Malayalam: "തത്സമയ ട്രാക്കിംഗ് ഓഫാക്കുക", Hindi: "लाइव ट्रैकिंग बंद करें" },
  "start_sharing_location": { English: "Start sharing your location", Malayalam: "നിങ്ങളുടെ ലൊക്കേഷൻ പങ്കിടാൻ ആരംഭിക്കുക", Hindi: "अपना स्थान साझा करना प्रारंभ करें" },
  "call_for_help": { English: "Call for Help", Malayalam: "സഹായത്തിനായി വിളിക്കുക", Hindi: "मदद के लिए पुकारें" },
  "calling_help": { English: "Calling...", Malayalam: "വിളിക്കുന്നു...", Hindi: "कॉल किया जा रहा है..." },
  "help_is_coming": { English: "Help is coming!", Malayalam: "സഹായം ഉടൻ എത്തും!", Hindi: "मदद आ रही है!" },
  "sos_hint": { English: "Tap and hold for emergency SOS", Malayalam: "അടിയന്തിര SOS-നായി അമർത്തിപ്പിടിക്കുക", Hindi: "आपातकालीन एसओएस के लिए टैप करके रखें" },
  "sos_confirmed": { English: "Emergency services have been notified.", Malayalam: "അടിയന്തിര സേവനങ്ങളെ വിവരം അറിയിച്ചിട്ടുണ്ട്.", Hindi: "आपातकालीन सेवाओं को सूचित कर दिया गया है।" },
  "trusted_contacts": { English: "Trusted Contacts", Malayalam: "വിശ്വസ്തരായ കോൺടാക്റ്റുകൾ", Hindi: "विश्वसनीय संपर्क" },
  "edit_list": { English: "Edit List", Malayalam: "ലിസ്റ്റ് തിരുത്തുക", Hindi: "सूची संपादित करें" },
  "contact_mom": { English: "Mom", Malayalam: "അമ്മ", Hindi: "माँ" },
  "contact_dad": { English: "Dad", Malayalam: "അച്ഛൻ", Hindi: "पिताजी" },
  "skill_tree_title": { English: "Career Roadmap", Malayalam: "കരിയർ റോഡ്മാപ്പ്", Hindi: "करियर रोडमैप" },
  "unlock_paths": { English: "Unlock new sectors", Malayalam: "പുതിയ മേഖലകൾ അൺലോക്ക് ചെയ്യുക", Hindi: "नए क्षेत्रों को अनलॉक करें" },
  "checklist": { English: "OPERATIONAL CHECKLIST", Malayalam: "പ്രവർത്തന ചെക്ക്‌ലിസ്റ്റ്", Hindi: "परिचालन चेकलिस्ट" },
  "complete_daily_tasks": { English: "MISSION_LOGS // TASK VERIFICATION", Malayalam: "മിഷൻ ലോഗുകൾ // ടാസ്ക് സ്ഥിരീകരണം", Hindi: "मिशन लॉग // कार्य सत्यापन" },
  "id": { English: "ID", Malayalam: "ഐഡി", Hindi: "आईडी" },
  "worker": { English: "Worker", Malayalam: "തൊഴിലാളി", Hindi: "श्रमिक" },
  "concludedStatus": { English: "Active", Malayalam: "സജീവം", Hindi: "सक्रिय" },
  "active_partner": { English: "AUTHORIZED PERSONNEL", Malayalam: "അംഗീകൃത വ്യക്തികൾ", Hindi: "अधिकृत कर्मी" },
  "assistant_greeting": { English: "NEURAL_LINK ESTABLISHED. How can I assist with your deployment today? 😊", Malayalam: "ന്യൂറൽ ലിങ്ക് സ്ഥാപിച്ചു. ഇന്ന് ഞാൻ വിന്യാസത്തിൽ എങ്ങനെ സഹായിക്കണം? 😊", Hindi: "न्यूरल लिंक स्थापित। आज मैं आपके परिनियोजन में कैसे सहायता कर सकता हूँ? 😊" },
  "prompt_earnings": { English: "Show me my earnings summary.", Malayalam: "എന്റെ വരുമാന സംഗ്രഹം കാണിക്കുക.", Hindi: "मुझे मेरी कमाई का सारांश दिखाएं।" },
  "check_in_help": { English: "DEPLOYMENT", Malayalam: "വിന്യാസം", Hindi: "परिनियोजन" },
  "prompt_checkin": { English: "How do I check in for your shift?", Malayalam: "ഞാൻ എങ്ങനെ ഷിഫ്റ്റിൽ ചെക്ക് ഇൻ ചെയ്യും?", Hindi: "मैं अपनी शिफ्ट के लिए कैसे चेक-इन करूं?" },
  "find_jobs": { English: "MISSIONS", Malayalam: "ദൗത്യങ്ങൾ", Hindi: "मिशन" },
  "prompt_find_jobs": { English: "Best gigs near me right now?", Malayalam: "എനിക്ക് ചുറ്റുമുള്ള മികച്ച ജോലികൾ ഏതൊക്കെയാണ്?", Hindi: "मेरे पास अभी सबसे अच्छे गिग्स कौन से हैं?" },
  "safety_guide": { English: "PROTOCOLS", Malayalam: "പ്രോട്ടോക്കോളുകൾ", Hindi: "प्रोटोकॉल" },
  "prompt_safety": { English: "What are the safety rules?", Malayalam: "സുരക്ഷാ നിയമങ്ങൾ എന്തൊക്കെയാണ്?", Hindi: "सुरक्षा नियम क्या हैं?" },
  "navigating_to": { English: "SURE. RE-ROUTING TO", Malayalam: "ശരി. റീ-റൂട്ട് ചെയ്യുന്നു", Hindi: "अवश्य। पुन: मार्ग निर्धारण" },
  "go_to": { English: "GO TO", Malayalam: "പോകുക", Hindi: "पर जाएं" },
  "bot_default": { English: "I'M HERE TO ASSIST.", Malayalam: "സഹായിക്കാൻ ഞാൻ ഇവിടെയുണ്ട്.", Hindi: "मैं यहाँ सहायता के लिए हूँ।" },
  "trouble_connecting": { English: "SIGNAL INTERFERENCE. PLEASE RETRANSMIT.", Malayalam: "സിഗ്നൽ തടസ്സം. ദയവായി വീണ്ടും അയക്കുക.", Hindi: "सिग्नलों में हस्तक्षेप। कृपया पुनः प्रेषित करें।" },
  "genie_assistant": { English: "NEURAL CORE", Malayalam: "ന്യൂറൽ കോർ", Hindi: "न्यूरल कोर" },
  "online_ready": { English: "LINK_STABLE", Malayalam: "ലിങ്ക് സുസ്ഥിരമാണ്", Hindi: "लिंक स्थिर" },
  "active_label": { English: "OPS", Malayalam: "ഓപ്‌സ്", Hindi: "ऑप्स" },
  "applicants": { English: "CANDIDATE POOL", Malayalam: "ഉദ്യോഗാർത്ഥികളുടെ കൂട്ടം", Hindi: "उम्मीदवार पूल" },
  "review_applications": { English: "Vetting & Recruitment Hub", Malayalam: "അവലോകനവും റിക്രൂട്ട്‌മെന്റ് ഹബും", Hindi: "जांच और भर्ती हब" },
  "call": { English: "CONTACT", Malayalam: "ബന്ധപ്പെടുക", Hindi: "संपर्क करें" },
  "reject": { English: "DECLINE", Malayalam: "നിരസിക്കുക", Hindi: "अस्वीकार करें" },
  "hire_now": { English: "AUTHORIZE DEPLOYMENT", Malayalam: "വിന്യാസത്തിന് അനുമതി നൽകുക", Hindi: "परिनियोजन अधिकृत करें" },
  "caught_up": { English: "QUEUE CLEAR", Malayalam: "ക്യൂ പൂർണ്ണമായും ഒഴിവായി", Hindi: "कतार साफ" },
  "no_pending": { English: "All operational requests processed.", Malayalam: "എല്ലാ പ്രവർത്തന അഭ്യർത്ഥനകളും പ്രോസസ്സ് ചെയ്തു.", Hindi: "सभी परिचालन अनुरोधों को संसाधित किया गया।" },
  "dark_mode": { English: "Dark Mode", Malayalam: "ഡാർക്ക് മോഡ്", Hindi: "डार्क मोड" },
  "privacy_safety": { English: "Privacy & Safety", Malayalam: "സ്വകാര്യതയും സുരക്ഷയും", Hindi: "गोपनीयता और सुरक्षा" },
  "detailed_info": { English: "Detailed Info", Malayalam: "വിശദമായ വിവരം", Hindi: "विस्तृत जानकारी" },
  "save_btn": { English: "Save", Malayalam: "സംരക്ഷിക്കുക", Hindi: "सहेजें" },
  "skills": { English: "Skills", Malayalam: "കഴിവുകൾ", Hindi: "कौशल" }
};

const otherLanguagesShortJobs = {
  "Bengali": { missions_short: "চাকরি" },
  "Marathi": { missions_short: "नोकऱ्या" },
  "Telugu": { missions_short: "ఉద్యోగాలు" },
  "Tamil": { missions_short: "പണികൾ" }, // Tamil uses பணிகள்
  "Gujarati": { missions_short: "નોકરીઓ" },
  "Urdu": { missions_short: "ملازمتیں" },
  "Kannada": { missions_short: "ಕೆಲಸಗಳು" },
  "Odia": { missions_short: "କାର୍ଯ୍ୟ" }
};

const urduExtras = {
  "export_id": "ایکسپورٹ آئی ڈی",
  "generate_vision": "ژن کی تیاری",
  "generate_bio": "بائیو جنریٹ کریں"
};

// Merge into TRANSLATIONS object
const languages = Object.keys(TRANSLATIONS);

languages.forEach(lang => {
  const langObj = TRANSLATIONS[lang];

  // 1. Merge missing keys (from missing_map.json plus extra profile/setting keys)
  Object.keys(newTranslations).forEach(key => {
    if (lang === 'English') {
      langObj[key] = newTranslations[key].English;
    } else if (lang === 'Malayalam') {
      langObj[key] = newTranslations[key].Malayalam;
    } else if (lang === 'Hindi') {
      langObj[key] = newTranslations[key].Hindi;
    } else {
      // Other languages fallback to English to prevent missing key errors in audits
      langObj[key] = newTranslations[key].English;
    }
  });

  // 2. Add missions_short
  if (lang === 'English') {
    langObj['missions_short'] = 'JOBS';
  } else if (lang === 'Malayalam') {
    langObj['missions_short'] = 'ജോലികൾ';
  } else if (lang === 'Hindi') {
    langObj['missions_short'] = 'नौकरियां';
  } else if (otherLanguagesShortJobs[lang]) {
    langObj['missions_short'] = otherLanguagesShortJobs[lang].missions_short;
  } else {
    langObj['missions_short'] = 'JOBS';
  }

  // 3. Urdu specific extras
  if (lang === 'Urdu') {
    Object.keys(urduExtras).forEach(key => {
      langObj[key] = urduExtras[key];
    });
  }
});

// Write updated translations.js back
const outputContent = 'export const LANGUAGES = ' + JSON.stringify(LANGUAGES, null, 2) + ';\n\nexport const TRANSLATIONS = ' + JSON.stringify(TRANSLATIONS, null, 2) + ';\n';
fs.writeFileSync(filePath, outputContent, 'utf-8');

console.log('Successfully merged all translations!');
